# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  integrate:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        repository: maxzer0/schort
        
    - name: Copy the checked out repository #no idea how to / lazy to change the pathing also this is a locally run project w/e
      run: cp /opt/actions-runner/_work/schort/schort/* /opt/schort/ -Rf

    # Runs a single command using the runners shell
    - name: Restart schort service
      run: sudo systemctl restart schort

    # Runs a set of commands using the runners shell
    - name: Restart nginx service
      run: sudo systemctl restart nginx
